
#' Label Users Using a Local LLM
#'
#' This function uses a locally hosted large language model (LLM) through the 
#' \pkg{rollama} interface to automatically generate structured annotations for users 
#' based on their sampled posts. It applies a few-shot prompting setup with examples 
#' and a predefined schema to produce machine-readable JSON output describing each user.
#'
#' The model should run via an active \emph{Ollama} Docker container with GPU (CUDA) support.
#' Use `system("docker ps")` to verify that Ollama is running, and ensure that the 
#' desired model (e.g., `"llama3.1:8b"`) has been pulled via Ollama before executing this function.
#'
#' @param groups_data A list containing at least the element \code{user_labels}, 
#' typically produced by [sample_user_text()]. This element must include a column \code{text} 
#' with sampled user content and an \code{account_id} column.
#' @param model Character string. Name of the local LLM model to be queried via Ollama. 
#' Default is \code{"llama3.1:8b"}.
#' @param prompt Optional character string providing user-facing task instructions 
#' (defaults to the internal \code{prompts$prompt_user}).
#' @param system Optional character string defining the system-level instruction to guide model behavior 
#' (defaults to the internal \code{prompts$system_user}).
#' @param example Optional character vector containing example input texts 
#' (defaults to \code{examples$example_user_text}).
#' @param answer Optional character vector containing corresponding example model outputs 
#' (defaults to \code{examples$example_user_answer}).
#' @param schema Optional JSON-like list defining the expected output structure 
#' (defaults to \code{schemata$schema_user}).
#' @param retries Integer. Maximum number of re-query attempts for responses that fail JSON validation. 
#' Default is \code{3}.
#' @param retry_trunc Integer. Character limit for truncating user text during retry attempts to prevent 
#' context overflow. Default is \code{4000}.
#' @param seed Integer. Random seed used for model sampling; incremented by 1 on each retry. Default is \code{42}.
#' @param temp Numeric. Sampling temperature for model generation (0 = deterministic). Default is \code{0.0}.
#' @param keep_description_json Logical. If \code{FALSE} (default), extracts and concatenates sentences from 
#' structured description objects into clean text. If \code{TRUE}, preserves JSON structure as text. Only relevant 
#' when description is returned as a JSON object with sentence_1 through sentence_5 fields.
#' @param cache_path Optional character string; passed on to `rollama::query()` to save responses - to resume after interruption. 
#' @param verbose Logical. Whether to display progress messages and retry information. Default is \code{TRUE}.
#'
#' @return 
#' The input \code{groups_data} list with the \code{user_labels} element updated to include:
#' \describe{
#'   \item{\code{description}}{Concise summary generated by the model.}
#'   \item{\code{lang}}{Predicted language code (ISO format).}
#'   \item{\code{emotion_valence}}{Overall emotional tone ("positive", "negative", "neutral").}
#'   \item{\code{incivility}}{Presence of uncivil or offensive language ("yes", "no").}
#'   \item{\code{elaborate}}{Linguistic elaboration category ("simple", "moderate", or "elaborate").}
#'   \item{\code{confidence}}{Model-assessed confidence (0–1 scale).}
#'   \item{\code{topic_1}–\code{topic_5}}{Detected main topics.}
#'   \item{\code{pattern_1}–\code{pattern_3}}{Repeated emojis, slogans, or stylistic markers.}
#'   \item{\code{named_entity_1}–\code{named_entity_3}, \code{sentiment_1}–\code{sentiment_3}}{Named entities 
#'         and their corresponding sentiment labels.}
#'   \item{\code{is_valid_json}}{Logical flag indicating valid JSON structure in model output.}
#'   \item{\code{response}}{Raw model output (JSON string).}
#'   \item{\code{model}, \code{model_queried_at}, \code{model_total_duration}}{Metadata for reproducibility.}
#' }
#'
#' @details
#' The function constructs few-shot prompts by combining examples and instructions, sends them to the 
#' locally hosted model using [rollama::query()], and validates the returned JSON using \pkg{jsonlite}.
#' If a response fails validation, it retries up to \code{retries} times with shorter input text 
#' (\code{retry_trunc}) and incremented seed values.
#'
#' The schema guides the model to output structured JSON containing linguistic, emotional, and stylistic annotations 
#' for each user. Common fields include `description`, `lang`, `topic`, `named_entities`, `repetitive_patterns`, 
#' `emotion_valence`, `incivility`, `elaborate`, and `confidence`.
#'
#' Ollama must be accessible locally (e.g., via Docker). Use [rollama::ping_ollama()] to confirm connectivity.  
#'
#' @seealso 
#' [sample_user_text()], [rollama::query()], [rollama::make_query()], 
#' [jsonlite::fromJSON()], [data.table::as.data.table()]
#'
#' @export
label_users <- function(groups_data, 
                        model = "llama3.1:8b",
                        prompt = NULL,
                        system = NULL,
                        example = NULL,
                        answer = NULL,
                        schema = NULL,
                        retries = 3, 
                        retry_trunc = 4000, 
                        seed = 42,
                        temp = 0.0,
                        keep_description_json = FALSE,
                        cache_path = NULL,
                        verbose = TRUE) {
  
  if (!"user_labels" %in% names(groups_data)) {
    stop("No 'user_labels' found. Please first sample content by 'sample_user_text'.")
  }
  
  # Set prompts and examples
  if(is.null(prompt)){
    prompt_user <- prompts$prompt_user
  }else{
    prompt_user <- prompt
  }
  
  if(is.null(system)){
    system_user <- prompts$system_user
  }else{
    system_user <- system
  }
  
  if(is.null(example)){
    example_user_text <- examples$example_user_text
  }else{
    example_user_text <- example
  }
  
  if(is.null(answer)){
    example_user_answer <- examples$example_user_answer
  }else{
    example_user_answer <- answer
  }
  
  if(is.null(schema)){
    schema_user <- schemata$schema_user
  }else{
    schema_user <- schema
  }
  
  user_labels <- data.table::copy(groups_data$user_labels)
  
  # Helper function to process description field (handles both string and object formats)
  process_description <- function(desc, keep_json = FALSE) {
    if (is.null(desc)) return(NA_character_)
    
    # If description is already a string, return as-is
    if (is.character(desc)) return(desc)
    
    # If it's a list/object with sentence fields
    if (is.list(desc)) {
      sentence_names <- paste0("sentence_", 1:5)
      has_sentences <- all(sentence_names %in% names(desc))
      
      if (has_sentences) {
        if (keep_json) {
          # Return as JSON text (preserves structure)
          return(jsonlite::toJSON(desc, auto_unbox = TRUE))
        } else {
          # Extract and concatenate sentences
          sentences <- sapply(sentence_names, function(s) desc[[s]] %||% "", USE.NAMES = FALSE)
          # Remove empty sentences and join with space
          sentences <- sentences[sentences != ""]
          return(paste(sentences, collapse = " "))
        }
      }
    }
    
    # Fallback for unexpected formats
    return(NA_character_)
  }
  
  if (!requireNamespace("rollama", quietly = TRUE)) {
    stop("Package 'rollama' is required for this function. Please install it.")
  }
  
  ping_res <- try(rollama::ping_ollama(), silent = TRUE)
  if (!ping_res[[1]]) stop("Ollama is not running.")
  
  example_resp <- tibble::tibble(
    text = paste0("Annotate:", example_user_text), 
    answer = example_user_answer
  )
  
  retry <- 0
  res_all <- list()
  user_current <- user_labels
  
  for (retry in 0:retries) {
    
    if (verbose) cli::cli_inform("Retry round {retry}. Querying {nrow(user_current)} users...")
    
    queries <- rollama::make_query(
      text = paste0("\n### EXAMPLES END ###\n\n", ### Clarify example boundaries to prevent context contamination
                    "### NEW INPUT ###\n",
                    "Annotate: \n",
                    user_current$text),
      template = "\n{text}\n{prompt}",
      prompt = prompt_user,
      system = paste0(system_user, 
                      "\n### EXAMPLES START ###\n"),
      example = example_resp
    )

    if(!is.null(cache_path)){
      if(!dir.exists(cache_path)) dir.create(cache_path, recursive = T, showWarnings = F)
      cache_paths <- file.path(cache_path, paste0(user_current$account_id, ".json"))
    }else{
      cache_paths <- NULL
    }

    responses <- rollama::query(
      q = queries,
      model = model,
      stream = FALSE, 
      output = "response",
      cache = cache_paths,
      model_params = list(seed = seed + retry, temperature = temp),
      verbose = TRUE,
      format = schema_user
    )
    # Helper function to safely extract fields from responses (handles errors and NULLs)
    safe_extract <- function(resp, ..., type = "chr") {
      if (inherits(resp, "error")) {
        return(switch(type,
          "chr" = NA_character_,
          "dbl" = NA_real_,
          "lgl" = NA
        ))
      }
      
      # Use ... to pass multiple indices to pluck
      value <- purrr::pluck(resp, ..., .default = NULL)
      if (is.null(value)) {
        return(switch(type,
          "chr" = NA_character_,
          "dbl" = NA_real_,
          "lgl" = NA
        ))
      }
      value
    }

    res_df <- user_current |>
      dplyr::mutate(
        # Extract response metadata safely
        response = purrr::map_chr(responses, ~ safe_extract(.x, "message", "content")),
        model = purrr::map_chr(responses, ~ safe_extract(.x, "model")),
        model_queried_at = purrr::map_chr(responses, ~ safe_extract(.x, "created_at")),
        model_total_duration = purrr::map_dbl(responses, ~ safe_extract(.x, "total_duration", type = "dbl"))
      ) |>
      dplyr::mutate(
        # Parse JSON with error handling
        parsed_json = purrr::map(
          response,
          ~ tryCatch(jsonlite::fromJSON(.x), error = function(e) NULL)
        ),
        # Validate JSON safely (handle NA responses)
        is_valid_json = purrr::map_lgl(response, ~ {
          if (is.na(.x)) return(FALSE)
          jsonlite::validate(.x)
        }),
        
        # --- Scalar fields ---
        description = purrr::map_chr(parsed_json, ~ process_description(.x$description, keep_description_json)),
        lang = purrr::map_chr(parsed_json, ~ .x$lang %||% NA_character_),
    #    emotion_valence = purrr::map_chr(parsed_json, ~ .x$emotion_valence %||% NA_character_),
        incivility = purrr::map_chr(parsed_json, ~ .x$incivility %||% NA_character_),
        elaborate = purrr::map_chr(parsed_json, ~ .x$elaborate %||% NA_character_),
        confidence = purrr::map_dbl(parsed_json, ~ .x$confidence %||% NA_real_)
      ) |>
      dplyr::mutate(
        # --- Topics ---
        topic = purrr::map(parsed_json, ~ base::unlist(.x$topic) %||% character()),
        topic_1 = purrr::map_chr(topic, ~ .x[1] %||% NA_character_),
        topic_2 = purrr::map_chr(topic, ~ .x[2] %||% NA_character_),
        topic_3 = purrr::map_chr(topic, ~ .x[3] %||% NA_character_),
        topic_4 = purrr::map_chr(topic, ~ .x[4] %||% NA_character_),
        topic_5 = purrr::map_chr(topic, ~ .x[5] %||% NA_character_),
        
        # --- Repetitive patterns ---
        repetitive_patterns = purrr::map(parsed_json, ~ base::unlist(.x$repetitive_patterns) %||% character()),
        pattern_1 = purrr::map_chr(repetitive_patterns, ~ .x[1] %||% NA_character_),
        pattern_2 = purrr::map_chr(repetitive_patterns, ~ .x[2] %||% NA_character_),
        pattern_3 = purrr::map_chr(repetitive_patterns, ~ .x[3] %||% NA_character_),
        
        # --- Named entities ---
        named_entities = purrr::map(parsed_json, ~ base::as.data.frame(.x$named_entities) %||% base::data.frame()),
        named_entity_1 = purrr::map_chr(named_entities, ~ .x$entity[1] %||% NA_character_),
        sentiment_1     = purrr::map_chr(named_entities, ~ .x$sentiment[1] %||% NA_character_),
        named_entity_2 = purrr::map_chr(named_entities, ~ .x$entity[2] %||% NA_character_),
        sentiment_2     = purrr::map_chr(named_entities, ~ .x$sentiment[2] %||% NA_character_),
        named_entity_3 = purrr::map_chr(named_entities, ~ .x$entity[3] %||% NA_character_),
        sentiment_3     = purrr::map_chr(named_entities, ~ .x$sentiment[3] %||% NA_character_),
        named_entity_4 = purrr::map_chr(named_entities, ~ .x$entity[4] %||% NA_character_),
        sentiment_4     = purrr::map_chr(named_entities, ~ .x$sentiment[4] %||% NA_character_),
        named_entity_5 = purrr::map_chr(named_entities, ~ .x$entity[5] %||% NA_character_),
        sentiment_5     = purrr::map_chr(named_entities, ~ .x$sentiment[5] %||% NA_character_)
        
      ) |>
      dplyr::select(
        -parsed_json,
        -topic,
        -repetitive_patterns,
        -named_entities
      )
    
    res_all[[retry + 1]] <- res_df
    
    if (all(res_df$is_valid_json)) {
      if (verbose) cli::cli_inform("All answers parsed successfully.")
      break
    }
    
    # Prepare failed users for retry
    failed_ids <- dplyr::filter(res_df, !is_valid_json)$account_id
    if (length(failed_ids) == 0 || retry == retries) {
      if (verbose) cli::cli_inform("Stopping after retry {retry}.")
      break
    }
    
    user_current <- user_labels |>
      dplyr::filter(account_id %in% failed_ids) |>
      dplyr::mutate(text = stringr::str_trunc(text, retry_trunc))
  }
  
  
  res_df <- dplyr::bind_rows(res_all)
  
  # De-duplicate (for parsing errors)
  res_df <- res_df |>
    dplyr::group_by(account_id) |>
    dplyr::slice_max(order_by = is_valid_json, n = 1, with_ties = FALSE) |>
    dplyr::ungroup() |> 
    dplyr::arrange(community, -user_share_comm)
  
  res_dt <- data.table::as.data.table(res_df)
  
  groups_data$user_labels <- res_dt
  
  return(groups_data)
}