utils::globalVariables(c(".",
                         ":=",
                         "end_time",
                         "time_dup",
                         "time",
                         "i.account_id", "i.post_id", "i.time",
                         "account_id",
                         "post_id",
                         "post_id_y",
                         "account_id_y",
                         "time_y",
                         ".BY",
                         "setNames",
                         "x",
                         "similarity",
                         ".N",
                         "time_diff",
                         "N",
                         "weight",
                         "algorithm",
                         ".SD",
                         "from",
                         "to",
                         "community",
                         "parameters",
                         "time_floored",
                         "total_N",
                         "name",
                         "community.x",
                         "community.y",
                         "..new_column_order"))


.datatable.aware <- TRUE