# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute cosine similarities
#'
#' This function computes the cosine similarity between the first row and all other rows of each matrix in a list.
#'
#' @param matrices_list A list of matrices where the row names are document IDs and columns are embeddings.
#' @param threshold A threshold value for the cosine similarity.
#' @return A list of data frames, each containing the document ID pairs and their cosine similarity values.
#' @export
#' 
compute_cosine_similarities <- function(matrices_list, threshold) {
    .Call(`_coorsim_compute_cosine_similarities`, matrices_list, threshold)
}

#' Query Embedding Subset
#'
#' This function takes a NumericMatrix and a list of post ID lists, 
#' and returns a list of NumericMatrix subsets where each subset corresponds to 
#' the rows in the input matrix matched by the post IDs in each list.
#'
#' @param m A NumericMatrix containing the embedding data with row names.
#' @param post_id_lists A List of CharacterVector objects, where each CharacterVector
#' represents a set of post IDs.
#' @return A List of NumericMatrix objects. Each matrix in the list contains the
#' rows from the input matrix \code{m} that correspond to the post IDs in the
#' corresponding element of \code{post_id_lists}.
#' @export
#'
query_embedding <- function(m, post_id_lists) {
    .Call(`_coorsim_query_embedding`, m, post_id_lists)
}

#' Query Embeddings and Compute Cosine Similarities
#'
#' This function takes a numeric matrix containing embeddings and a list of post ID lists. 
#' It performs two tasks sequentially to conserve memory:
#' 1. Queries the embeddings for each post ID list.
#' 2. Computes the cosine similarities between the first embedding and all other embeddings within each subset.
#' 
#' The function returns a list of data frames where each data frame contains post ID pairs and their cosine similarities that exceed the given threshold.
#' 
#' @param m A NumericMatrix containing the embedding data with row names representing post IDs.
#' @param post_id_lists A List of CharacterVector objects, where each CharacterVector represents a set of post IDs to query in the embedding matrix.
#' @param threshold A double value representing the threshold for cosine similarity. Only similarities above this threshold are included in the output.
#' @return A List of DataFrames. Each data frame contains three columns: "post_id" (the first post ID in the pair), "post_id_y" (the second post ID in the pair), and "similarity" (the cosine similarity between them).
#' @export
query_and_compute_similarities <- function(m, post_id_lists, threshold) {
    .Call(`_coorsim_query_and_compute_similarities`, m, post_id_lists, threshold)
}

#' Set number of threads
#'
#' @param threads Integer, setting the number of threads for parallel processing.
#'
set_num_threads <- function(threads) {
    invisible(.Call(`_coorsim_set_num_threads`, threads))
}

#' Query Embeddings and Compute Cosine Similarities with TBB
#'
#' This function takes a numeric matrix containing embeddings and a list of post ID lists.
#' It performs two tasks sequentially to conserve memory:
#' 1. Queries the embeddings for each post ID list.
#' 2. Computes the cosine similarities between the first embedding and all other embeddings within each subset.
#'
#' The function returns a list of data frames where each data frame contains post ID pairs and their cosine similarities that exceed the given threshold.
#'
#' @param m A NumericMatrix containing the embedding data with row names representing post IDs.
#' @param post_id_lists A List of CharacterVector objects, where each CharacterVector represents a set of post IDs to query in the embedding matrix.
#' @param threshold A double value representing the threshold for cosine similarity. Only similarities above this threshold are included in the output.
#' @return A List of DataFrames. Each data frame contains three columns: "post_id" (the first post ID in the pair), "post_id_y" (the second post ID in the pair), and "similarity" (the cosine similarity between them).
#' @export
query_and_compute_similarities_tbb <- function(m, post_id_lists, threshold) {
    .Call(`_coorsim_query_and_compute_similarities_tbb`, m, post_id_lists, threshold)
}

